### ISSUE TITLE
PeLib32.lib not found

### ISSUE THREAD

**Issue by Django-Fakkeldij** [nickcano/RelocBonus#3]
I'm a bit of a noob but when I try to compile this in VS2019 I get this error and I have no idea how to solve it...

![image](https://user-images.githubusercontent.com/75489918/101179415-75658780-364a-11eb-90fe-4d891b87a6ff.png)

**Comment by Django-Fakkeldij** [comment]
Nvm, was being a noob (as I predicted) you have to compile the deps first. xD

**Comment by techhotspot** [comment]
How exactly did you do that, i tried Googleing but couldn't figure it out.
